CREATE TABLE PRICES(
	ID INTEGER NOT NULL AUTO_INCREMENT,
	BRAND_ID BIGINT,
	START_DATE TIMESTAMP,
	END_DATE TIMESTAMP,
	PRICE_LIST BIGINT,
	PRODUCT_ID BIGINT,
	PRIORITY INTEGER,
	PRICE DECIMAL(5,2),
	CURR VARCHAR(10),
	PRIMARY KEY (ID)
);